// <auto-generated />
using System;
using BYSCORE.Dao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BYSCORE.API.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20190103084428_3")]
    partial class _3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BYSCORE.Entity.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnName("application")
                        .HasMaxLength(50);

                    b.Property<string>("Callsite")
                        .HasColumnName("callsite")
                        .HasMaxLength(512);

                    b.Property<string>("Exception")
                        .HasColumnName("exception")
                        .HasMaxLength(512);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnName("level")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Logged")
                        .HasColumnName("logged");

                    b.Property<string>("Logger")
                        .HasColumnName("logger")
                        .HasMaxLength(250);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message")
                        .HasMaxLength(512);

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("applicationlog");
                });

            modelBuilder.Entity("BYSCORE.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("AddTime")
                        .HasColumnName("addtime");

                    b.Property<int>("Category")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasMaxLength(500);

                    b.Property<decimal>("Discout")
                        .HasColumnName("discout");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("isdelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(20);

                    b.Property<decimal>("Price")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");
                });
#pragma warning restore 612, 618
        }
    }
}
